### ISSUE TITLE
No instructions, Click on What and Where?    "As you click It cycles through the audible tabs even if they are on multiple browser windows!"

### ISSUE THREAD

**Issue by Mintopia1st** [cyberst/go-to-sound-tab#2]

**Comment by cyberst** [comment]
![image](https://github.com/cyberst/go-to-sound-tab/assets/19276191/39637db9-5a21-45e2-8f12-b969672d102b)


Our extension logo should be next to the address bar of your browser. If not so, you should be able to add it there through the extension settings of your browser.
